title: 9Anime Stream
url: "https://aniscape09-crypto.github.io"
baseurl: "/Hianime" # Add your repo name here

collections:
  anime:
    output: true
    permalink: /anime/:path/

paginate: 24
paginate_path: "/home/page:num/"
